### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by gikosei** [RolfRolles/HexRaysDeob#12]
Hi. I've tried to install your plugin in my Ida Pro (Hexrays and Ida version both 7.2).
I'm kinda new to IDA so I just tried to copy .dll file(and other src, hdr files) into %IDA_DIR%/plugins directory and modified plugins.cfg file as that is the general way everyone says in Google, but it didn't worked and I cannot find the plugin in IDA.
Is there another way to install your plugin or am I doing it wrong?

**Comment by seeker25** [comment]
Edit.. bad info sorry

**Comment by RolfRolles** [comment]
If you're new to IDA, I wouldn't recommend using this plugin. It has a specific purpose: to break the obfuscator in [this blog entry](http://www.hexblog.com/?p=1248). It is not a general-purpose plugin.
