### ISSUE TITLE
Ida 6.8 and 7.0

### ISSUE THREAD

**Issue by ericsia** [RolfRolles/HexRaysDeob#13]
Correct me if I'm wrong, I placed it in plugin folder. When I want to load plugin or I find the menu I didn't see it.
Maybe a few screenshot of your brilliant plugin will be helpful

**Comment by RolfRolles** [comment]
This is not a general-purpose plugin. It has one goal only: to deobfuscate the sample in [the blog entry that accompanied its release](http://www.hexblog.com/?p=1248). That blog entry has many screenshots on what the plugin does and how it works. If you're using it for any purpose other than deobfuscating that sample, you're on your own. I'm not supporting anything but that use-case.

The headline of your issue says "Ida 6.8 and 7.0", although the body of your issue doesn't make any reference to IDA versions. By extrapolation, let me add that Hex-Rays 7.1 is the minimum version that will work, as this was when the microcode API was released. (That information is also mentioned in [the blog entry](http://www.hexblog.com/?p=1248).)
