### ISSUE TITLE
Building HexRaysDeob for IDA 7.5

### ISSUE THREAD

**Issue by tomr123** [RolfRolles/HexRaysDeob#17]
Hi,
I'm having trouble building this plugin with the latest SDK.
there is some issue with ObfCompilerOptimizer instantiation.

did any body try building this plugin for IDA 7.5?

Thanks,
Tom

**Comment by RolfRolles** [comment]
I'm not maintaining this project anymore. Please use [PyHexRaysDeob](https://github.com/idapython/pyhexraysdeob) instead.
