### ISSUE TITLE
Compiling for IDA 7.3 on MacOS

### ISSUE THREAD

**Issue by jags613** [RolfRolles/HexRaysDeob#9]
Any guidance compiling for 7.3 on Mac?
Makefile crashes out early, not finding type definitions that are contained within the SDK.

`c++ -m64 -arch x86_64 -mmacosx-version-min=10.9 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -std=c++11 -g -pipe -O2 -I../../include/ -DNDEBUG -DNO_OBSOLETE_FUNCS -D_FORTIFY_SOURCE=2 -D__MAC__ -fPIC -fdata-sections -fdiagnostics-show-option -ffunction-sections -fno-caret-diagnostics -fno-strict-aliasing -fomit-frame-pointer -fstack-protector-strong -fvisibility-inlines-hidden -fvisibility=hidden -fwrapv -Wall -Werror=format-nonliteral -Werror=format-security -Wextra -Wformat=2 -Wshadow -Wunused -Wno-char-subscripts -Wno-dynamic-class-memaccess -Wno-format-y2k -Wno-int-to-pointer-cast -Wno-invalid-source-encoding -Wno-logical-not-parentheses -Wno-logical-op-parentheses -Wno-missing-field-initializers -Wno-null-conversion -Wno-parentheses-equality -Wno-self-assign -Wno-sign-compare -Wno-unused-const-variable -Wno-unused-function -Wno-unused-private-field -Wno-unused-variable -Wno-varargs -fno-rtti -c -o obj/x64_mac_gcc_32/AllocaFixer.o AllocaFixer.cpp
In file included from AllocaFixer.cpp:18:
In file included from ../../include/hexrays.hpp:14:
In file included from ../../include/idp.hpp:12:
../../include/nalt.hpp:733:3: error: unknown type name 'op_dtype_t'; did you mean 'idtype_t'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:83:3: note: 'idtype_t' declared here
In file included from AllocaFixer.cpp:18:
In file included from ../../include/hexrays.hpp:14:
In file included from ../../include/idp.hpp:12:
../../include/nalt.hpp:744:24: error: unknown type name 'op_dtype_t'; did you mean 'idtype_t'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:83:3: note: 'idtype_t' declared here
In file included from AllocaFixer.cpp:18:
In file included from ../../include/hexrays.hpp:14:
In file included from ../../include/idp.hpp:12:
../../include/nalt.hpp:793:7: error: cannot initialize a member subobject of type 'idtype_t' with an rvalue of type 'int'
In file included from AllocaFixer.cpp:18:
In file included from ../../include/hexrays.hpp:14:
In file included from ../../include/idp.hpp:15:
In file included from ../../include/ua.hpp:11:`

**Comment by RolfRolles** [comment]
I haven't upgraded to 7.3 yet, or attempted to build the plugin, so I can't specifically advise about that. However, it appears this is a build environment problem on your end. Notice it's giving errors in `nalt.hpp` -- it's saying that the errors are originating in the IDA SDK. Make sure you can compile some sample plugins from the IDA SDK before trying to compile my plugin.
